language: go

go:
  - 1.x
  - 1.12.x

env:
  - GO111MODULE=on

install:
  - make install-tools

script:
  - make coverage.out
  - make lint
  - make format
  - git diff --exit-code
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN; fi

sudo: false
